### ISSUE TITLE
US-MIDA-PJM (US_PJM.py) Zone production parser is down

### ISSUE THREAD

**Issue by EarthlyAlien** [electricitymap/electricitymap-contrib#4155]
### Description
This is an error report for PJM Interconnection (US-MIDA-PJM).

**Issues:**
- No recent data found for production parser
- pjm.com domain seems to be down entirely.

### Suggestions

- Try running the parser locally using the command poetry run test_parser US-MIDA-PJM production
- [Explore the runtime logs](https://storage.googleapis.com/electricitymap-parser-logs/US-MIDA-PJM.html)

You can see an overview of all parser issues [here](https://github.com/tmrowco/electricitymap-contrib/wiki/Parser-issues).

**Comment by VIKTORVAV99** [comment]
hmm pjm.com seems to be working just fine for me and so is the parser.

It does seem to have intermittent errors though but the estimation model filled in those hours.

**Comment by EarthlyAlien** [comment]
@VIKTORVAV99 - Please take a look at the error message below.

I was using `poetry run test_parser US-MIDA-PJM production` and I do have an API Key for PJM as well.

`2022-05-19 13:51:47,472 DEBUG    urllib3.connectionpool         Starting new HTTP connection (1): www.pjm.com:80
Traceback (most recent call last):
  File "/home/chaivan/electricitymap-contrib/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/chaivan/electricitymap-contrib/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chaivan/electricitymap-contrib/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/chaivan/electricitymap-contrib/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/chaivan/electricitymap-contrib/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/home/chaivan/electricitymap-contrib/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/home/chaivan/electricitymap-contrib/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f1d39a64730>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chaivan/electricitymap-contrib/.venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/chaivan/electricitymap-contrib/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/home/chaivan/electricitymap-contrib/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='www.pjm.com', port=80): Max retries exceeded with url: /markets-and-operations.aspx (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1d39a64730>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/chaivan/electricitymap-contrib/.venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/chaivan/electricitymap-contrib/.venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/chaivan/electricitymap-contrib/.venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/chaivan/electricitymap-contrib/.venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/chaivan/electricitymap-contrib/test_parser.py", line 66, in test_parser
    res = parser(
  File "/home/chaivan/electricitymap-contrib/parsers/US_PJM.py", line 167, in fetch_production
    extracted = extract_data(session=None)
  File "/home/chaivan/electricitymap-contrib/parsers/US_PJM.py", line 59, in extract_data
    req = requests.get(url)
  File "/home/chaivan/electricitymap-contrib/.venv/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/chaivan/electricitymap-contrib/.venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/chaivan/electricitymap-contrib/.venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/chaivan/electricitymap-contrib/.venv/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/chaivan/electricitymap-contrib/.venv/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.pjm.com', port=80): Max retries exceeded with url: /markets-and-operations.aspx (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1d39a64730>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))`

**Comment by VIKTORVAV99** [comment]
If you look at the runtime logs instead you can see while the parser is failing to get price, exchange data and consumption, and is still functioning for production so it's not down.

Now I don't have a PJM API key so I can't test it myself but I think this might be a local issue on your side.

**Comment by EarthlyAlien** [comment]
Apologies for the confusion then. I was trying to access the PJM's API from Asia region. It seems they blocked access to my region.

I tried to load the [pjm.com](http://www.pjm.com/markets-and-operations.aspx)/markets-and-operations.aspx via a US Proxy and it loaded fine. Thanks for the info, @VIKTORVAV99.
