### ISSUE TITLE
Cannot run parsers on Github Codespaces

### ISSUE THREAD

**Issue by steren** [electricitymap/electricitymap-contrib#4326]
I have followed the [local dev setup instructions](https://github.com/electricitymap/electricitymap-contrib/wiki/Set-up-local-environment)

After running `poetry install -E parsers`, when I run `poetry run test_parser FR production`, I get: 

```
$ poetry run test_parser FR production
/workspaces/electricitymap-contrib/.venv/lib/python3.10/site-packages/pandas/compat/__init__.py:124: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/python/latest/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspaces/electricitymap-contrib/test_parser.py", line 14, in <module>
    from parsers.lib.parsers import PARSER_KEY_TO_DICT
  File "/workspaces/electricitymap-contrib/parsers/lib/parsers.py", line 32, in <module>
    mod = importlib.import_module("parsers.%s" % mod_name)
  File "/opt/python/latest/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/workspaces/electricitymap-contrib/parsers/IN_MH.py", line 4, in <module>
    import cv2
  File "/workspaces/electricitymap-contrib/.venv/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/workspaces/electricitymap-contrib/.venv/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/opt/python/latest/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

Thanks to [Stackoverflow](https://stackoverflow.com/questions/55313610/importerror-libgl-so-1-cannot-open-shared-object-file-no-such-file-or-directo), I understood I needed to run need to run `sudo apt-get install ffmpeg libsm6 libxext6  -y`

Is it expected? if so, should we capture this in the [setup local dev](https://github.com/electricitymap/electricitymap-contrib/wiki/Set-up-local-environment) page?

**Comment by VIKTORVAV99** [comment]
I think this is somewhat expected as GitHub codes paces uses very minimal images and this project don't have any pre-built images.

We could probably build a image with everything needed but I'm unsure about the costs and requirements for doing so I'll leave that up to the electricityMap team.

We could definitely update the wiki, I probably wouldn't put it in the local dev section but a dedicated codespaces section.

I think you could even do it yourself if you wanted to (since you already know the steps).

**Comment by steren** [comment]
I updated [this page](https://github.com/electricitymap/electricitymap-contrib/wiki/Set-up-local-environment), as the instructions can apply on any dev machine which doesnt have all required opencv deps

**Comment by steren** [comment]
I am also adding a dockerfile (https://github.com/electricitymap/electricitymap-contrib/pull/4328) to help with this in the future
